export const Strings = {
  my_appointments: 'Randevularım',
  header: 'Kullanıcı Bilgilerim',
  make_appointment: 'Randevu Al',
  my_barber_info: 'Kuaför Bilgilerim',
  password_hidden: '********',
  barber_add_panel: 'Kuaför Ekleme Paneli',
  are_you_women_barber: 'Kadın Kuaförü müsünüz ?',
  enter_barber_name: 'Kuaför Adını Yazın',
  enter_mail_address: 'Mail Adresinizi Yazın',
  enter_phone_number: 'Telefon Numaranızı Yazın (GSM)',
  enter_address: 'Adresinizi Yazın',
  barber_remove_panel: 'Kuaför Silme Paneli',
  barber_id_delete: 'Sileceğiniz kuafor idsi',
  delete: 'Sil',
  add: '     EKLE     ',
  user_add_panel: 'Kullanıcı Ekleme Paneli',
  add_user: 'Kullanıcı Ekle',
  edit_profile: 'Profili Düzenle',
  enter_password: 'Şifrenizi Girin',
  enter_password_again: 'Şifrenizi Tekrar Girin',
  update: 'Güncelle',
  enter_name: 'İsminizi Girin',
};
